name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build release artefacts
        run: make release RELEASE_VERSION=${GITHUB_REF#refs/tags/}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
          generate_release_notes: true
